### PR TITLE
Upload a CSS file in the website

### PR DESCRIPTION
**Pull request by ryanluzong**
This branch is already complete the design of our Website.

### CODE REVIEW

**Review by lsbaby06 — APPROVED** [review]

**Comment by lsbaby06** [comment]
Now our website is already COMPLETED! Thank You everyone for participating in the project! ❤️

**Comment by ryanluzong** [comment]
> Now our website is already COMPLETED! Thank You everyone for participating in the project! ❤️

Thank You! 😄

**Comment by joshuayadao** [comment]
Yayyy!! Thank you!!

**Comment by JMYadao** [comment]
Thank you!!

**Pull request merged**
